"""
Django settings for app_pj project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--e!0^c-#r2avg_r!s!@$#5o3vu!h!c5e*3f2$e&p=ss*%o#n#9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 問9-3 INSTALLED_APPS に bootstrap4,bootstrap_datepicker_plus.widgets を追加しましょう。
    'bootstrap4',
    'bootstrap_datepicker_plus.widgets',
    'todoapp',
    'accounts_app',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app_pj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 問9-4 TAMPLATES の OPTIONS に builtins を追加して下記の文を追加しましょう。
            'builtins':[
                'bootstrap4.templatetags.bootstrap4',
            ]
        },
    },
]

# 問9-5 bootstrp で jquery を使うための宣言を追加しましょう。
BOOTSTRAP4 = {
    'include_jquery': True,
}

WSGI_APPLICATION = 'app_pj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.postgresql',
        "NAME": 'postgres',
        "USER": 'postgres',
        "PASSWORD": 'password',
        "HOST": 'db',
        "PORT": 5432,
    }
}

# DBの日本語対応
DATABASE_OPTIONS = dict(init_command="SET NAMES 'utf8'")

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ja-JP'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 認証はデフォルトUserモデルで実施されるので、CustomUserモデルで認証できるように、「アプリケーション名.モデル名」を設定する
# AUTH_USER_MODEL定数にCustomUserモデル（accounts_app.CustomUser）を格納する
AUTH_USER_MODEL = 'accounts_app.CustomUser'

# ログインが必要なページに認証していないユーザがアクセスしたらリダイレクトさせる
# LOGIN_URL定数にログイン画面のパス（/accounts_app/login）を格納する
LOGIN_URL = '/accounts_app/login'
