# Generated by Django 3.2.18 on 2023-02-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadtime',
            new_name='deadline',
        ),
    ]
