# Generated by Django 4.1.7 on 2023-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_deadtime_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
